### ISSUE TITLE
AUTO_DATE_RANGE missing nightly data

### ISSUE THREAD

**Issue by bhammack** [arpanghosh8453/public-fitbit-projects#10]
Hey there, love the project.

I'm experiencing an issue where the fetcher does not pull data on a routine basis. This seems to occur every night from ~18:45 to 00:00 the following day local time (23:45 - 05:00 UTC, container time), despite the usage of `AUTO_DATE_RANGE`. Below is a copy of my docker-compose.yml configuration for the service, as well as a snapshot in Grafana indicating the data gaps. The data for these time periods is present and visible in the FitBit app. This does not appear to be an issue with the host, as restarting the container will back-fill the data by 24 hours. Logs do not appear to contain any errors.

Any ideas why this may be the case, and how to fix it? 

### Docker compose

```yaml
fitbit:
    image: thisisarpanghosh/fitbit-fetch-data:latest
    container_name: fitbit
    restart: unless-stopped
    volumes:
      - ./configs/fitbit/logs:/app/logs
      - ./configs/fitbit/tokens:/app/tokens
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FITBIT_LOG_FILE_PATH=/app/logs/fitbit.log
      - TOKEN_FILE_PATH=/app/tokens/fitbit.token
      - OVERWRITE_LOG_FILE=True
      - FITBIT_LANGUAGE='en_US'
      - INFLUXDB_VERSION = 1 # supported values are 1 and 2 
      - INFLUXDB_HOST=influxdb # for influxdb 1.x
      - INFLUXDB_PORT=8086 # for influxdb 1.x
      - INFLUXDB_USERNAME=fitbit_user # for influxdb 1.x
      - INFLUXDB_PASSWORD=fitbit_password # for influxdb 1.x
      - INFLUXDB_DATABASE=fitbit_database # for influxdb 1.x
      - CLIENT_ID=${FITBIT_CLIENT_ID}
      - CLIENT_SECRET=${FITBIT_CLIENT_SECRET}
      - DEVICENAME='Inspire3'
      - AUTO_DATE_RANGE=True
```

### Grafana

<img width="1501" alt="Screenshot 2024-02-26 at 9 56 35 AM" src="https://github.com/arpanghosh8453/public-fitbit-projects/assets/8301606/c623b712-3d7b-4d52-bac6-cbe8b102681c">
